apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
type: Opaque
stringData:
  SMTP_HOST: "mail.pi-lar.net:587"
  SMTP_USER: "shabnaz.khanam@pi-lar.net"
  SMTP_PASSWORD: "Sh01792119607!"
  SMTP_FROM_ADDRESS: "shabnaz.khanam@pi-lar.net"
  SMTP_FROM_NAME: "Grafana"
