alertmanager:
  alertmanagerSpec:
    configSecret: alertmanager-gmail-secret
grafana:
  adminUser: admin
  adminPassword: prom-operator

  grafana.ini:
    smtp:
      enabled: true
      host: mail.gmail.com:587
      user: your_gmail_address
      password: ${SMTP_PASSWORD}   
      skip_verify: true
      from_address: your_gmail_address
      from_name: Grafana
  envFromSecret: grafana-smtp-secret
